import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Sidebar from "@/components/common/Sidebar/Sidebar";
import { Layout } from "antd";
import { Footer, Content } from "antd/es/layout/layout";
import Navbar from "@/components/common/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <Layout className="h-dvh">
            <Sidebar />
            <Layout>
              <Navbar />
              <Content className="m-4">
                <div
                  style={{
                    minHeight: 360,
                  }}
                >
                  {children}
                </div>
              </Content>
              <Footer className="text-center">AnimeHaven ©{new Date().getFullYear()}</Footer>
            </Layout>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
